### ISSUE TITLE
get_receiver_robots_idでIndexError: list index out of rangeが発生した

### ISSUE THREAD

**Issue by ShotaAk** [SSL-Roots/consai_ros2#70]
consai vs consaiでテスト中にgame.pyが落ちました。
試合中にロボットの台数を減らしたので、それが影響したと考えられます。
もしくは、grsimとの通信が途絶えて、ロボット・フィールド情報が得られなくなったことも原因かもしれません、。

ログ：

```sh
[game.py-4] UNDEFINED REFEREE COMMAND!!!
[game.py-4] [INFO] [1682945091.611105543] [referee_parser]: force startによりinplayに変わります
[game.py-4] UNDEFINED REFEREE COMMAND!!!
[game.py-4] Traceback (most recent call last):
[game.py-4]   File "/home/shotaak/ros2_ws/install/consai_examples/lib/consai_examples/game.py", line 221, in <module>
[game.py-4]     main()
[game.py-4]   File "/home/shotaak/ros2_ws/install/consai_examples/lib/consai_examples/game.py", line 112, in main
[game.py-4]     decisions[role].inplay(robot_id)
[game.py-4]   File "/home/shotaak/ros2_ws/src/consai_ros2/consai_examples/consai_examples/decisions/goalie.py", line 62, in inplay
[game.py-4]     receiver_robots_id = self._field_observer.get_receiver_robots_id(robot_id)
[game.py-4]   File "/home/shotaak/ros2_ws/src/consai_ros2/consai_examples/consai_examples/field_observer.py", line 743, in get_receiver_robots_id
[game.py-4]     b_kai = 2 * ((intercept_from_passer_to_our_robot - their_robot_state[robot_id][1]) * slope_from_passer_to_our_robot - their_robot_state[robot_id][0])
[game.py-4] IndexError: list index out of range
[game.py-4] Exception in thread Thread-1 (spin):
[game.py-4] Traceback (most recent call last):
[game.py-4]   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
[ERROR] [game.py-4]: process has died [pid 7604, exit code 1, cmd '/home/shotaak/ros2_ws/install/consai_examples/lib/consai_examples/game.py --yellow --invert --goalie 0 --ros-args'].
[component_container_mt-1] [WARN] [1682945367.592792632] [controller]: Failed to extract ID:10 robot from detection_tracked msg.

```

**Comment by ShotaAk** [comment]
再現方法：

1. インプレイ状態にする
2. 相手ロボットの9番をOFFする（消失させる）
3. ボールを自チームディフェンスエリアに置く
4. 上記のエラーが発生する

**Comment by ShotaAk** [comment]
#73で解決
